version: '3.1'

services:
  springboot:
    image: sravanidockerhub/spring-boot-mongo-image:BUILD_TAG
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: springbootcontainer
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappnetwork  
   
  mongo:
    image: mongo
    container_name: springdbcontainer
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    driver: local
    
networks:
  springappnetwork:
    driver: bridge
