apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      name: springapppod
      labels:
        app: springapp
    spec:
      imagePullSecrets:
      - name: dockerregcred
      containers:
      - name: springappcontainer
        image: sravanidockerhub/privatespringbootrepo:tagname
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 128Mi
            cpu: 0.2
          limits:
            memory: 512Mi
            cpu: 0.5
        env:
        - name: MONGO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: springappconfig
              key: mongodbusername
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springappsecret
              key: mongodbpassword
        - name: MONGO_DB_HOSTNAME
          value: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbdeployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongodb
     spec:
       volumes:
       - name: mongodbdatavol
         persistentVolumeClaim:
           claimName: mongodbpvc
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
         env:
         - name: MONGO_INITDB_ROOT_USERNAME
           valueFrom:
             configMapKeyRef:
               name: springappconfig
               key: mongodbusername
         - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
               name: springappsecret
               key: mongodbpassword
         volumeMounts:
         - name: mongodbdatavol
           mountPath: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpvc
  namespace: test-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

